name: Block merge

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review
  deployment_status:

jobs:
  block-merge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout#v3

      - name: Toggle merge status
        id: toggle-merge-status
        run: |
          ENDPOINT_URL="${{ github.api_url }}/repos/${{ github.repository }}/deployments"
          STATUSES_URL=$(curl -s -X GET \
                              -H "Accept: application/vnd.github+json" \
                              -H "Authorization: Bearer ${TOKEN}"      \
                              -H "X-GitHub-Api-Version: 2022-11-28"    \
                              "$ENDPOINT_URL?sha=${{ github.sha }}" | jq -r '.[0].statuses_url')
          status=$(curl -s -X GET \
                        -H "Accept: application/vnd.github+json" \
                        -H "Authorization: Bearer ${TOKEN}"      \
                        -H "X-GitHub-Api-Version: 2022-11-28"    \
                        "$STATUSES_URL?per_page=1" | jq -r '.[0].state')
          if [ "$status" == 'active' ] || [ "$status" == 'inactive' ]; then
            echo '[INFO] related deployment is found.'
            exit 0
          else
            echo '[ERROR] related deployment is not found.'
            exit 1
          fi
