name: Block merge

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review
  deployment_status:

jobs:
  block-merge:
    runs-on: ubuntu-latest
    steps:
      - name: Toggle merge status
        id: toggle-merge-status
        run: |
          ENDPOINT_URL="${{ github.api_url }}/repos/${{ github.repository }}/deployments"
          curl -s -X GET \
                              -H "Accept: application/vnd.github+json" \
                              -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}"      \
                              -H "X-GitHub-Api-Version: 2022-11-28"    \
                              "$ENDPOINT_URL?sha=${{ github.sha }}"
          statuses_url=$(curl -s -X GET \
                              -H "Accept: application/vnd.github+json" \
                              -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}"      \
                              -H "X-GitHub-Api-Version: 2022-11-28"    \
                              "$ENDPOINT_URL?sha=${{ github.event.pull_request.head.sha }}" | jq -r '.[0].statuses_url')
          if echo "$statuses_url" | grep -q $ENDPOINT_URL; then
            echo '[INFO] related deployment is found.'
          else
            echo '[ERROR] related deployment is not found.'
            exit 1
          fi
          status=$(curl -s -X GET \
                        -H "Accept: application/vnd.github+json" \
                        -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}"      \
                        -H "X-GitHub-Api-Version: 2022-11-28"    \
                        "$statuses_url?per_page=1" | jq -r '.[0].state')
          if [ "$status" == 'active' ] || [ "$status" == 'inactive' ]; then
            echo '[INFO] related deployment status is ${status}.'
            exit 0
          else
            echo '[ERROR] related deployment status is not in [active, inactive].'
            exit 1
          fi
